apiVersion: v1
kind: Service
metadata:
    name: "aksresearch1-4d20"
    labels:
        app: "aksresearch1-4d20"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksresearch1-4d20"